const gulp = require('gulp')
const svgo = require('gulp-svgo')
const path = require('path')
const fs = require('fs')

const SRC_DIR = path.join(__dirname, 'src/icons')
const OPTIMIZED_DIR = path.join(__dirname, 'src/icons/optimized')
const DIST_DIR = path.join(__dirname, 'dist')

function clean(done) {
  if (fs.existsSync(DIST_DIR)) {
    fs.rmSync(DIST_DIR, { recursive: true, force: true })
  }
  done()
}

function optimizeSvg() {
  return gulp
    .src(`${SRC_DIR}/**/*.svg`)
    .pipe(
      svgo({
        plugins: [
          {
            name: 'preset-default',
            params: {
              overrides: {
                removeViewBox: false,
                removeDimensions: true,
                removeStyleElement: true,
                removeScriptElement: true,
                removeTitle: true,
                removeDesc: true,
                removeUselessDefs: true,
                removeEditorsNSData: true,
                removeEmptyAttrs: true,
                removeHiddenElems: true,
                removeEmptyText: true,
                convertColors: true,
                convertPathData: true,
                mergePaths: true,
                removeUnusedNS: true,
                sortAttrs: true,
                removeEmptyContainers: true,
                cleanupIds: true,
                minifyStyles: true,
                convertTransform: true,
                removeUnknownsAndDefaults: true,
                removeNonInheritableGroupAttrs: true,
                removeEmptyText: true,
                convertShapeToPath: true,
                convertEllipseToCircle: true,
                moveElemsAttrsToGroup: true,
                moveGroupAttrsToElems: true,
                collapseGroups: true,
                convertPathData: true,
                convertTransform: true,
                mergePaths: true,
                removeUnusedNS: true,
                sortDefsChildren: true,
                removeTitle: true,
                removeDesc: true,
              },
            },
          },
        ],
      })
    )
    .pipe(gulp.dest(OPTIMIZED_DIR))
}

function build() {
  return gulp
    .src('src/components/vue3/*.vue')
    .pipe(gulp.dest('dist/vue3'))
}

function copyTypes() {
  return gulp
    .src('src/index.d.ts')
    .pipe(gulp.dest('dist'))
}

function copyUniApp() {
  return gulp
    .src('src/components/uniapp/*.vue')
    .pipe(gulp.dest('dist/uniapp'))
}

async function buildNpm() {
  console.log('Building npm package...')
  
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true })
  }
  
  const vue3Dir = path.join(__dirname, 'src/components/vue3')
  const files = fs.readdirSync(vue3Dir).filter(f => f.endsWith('.vue'))
  
  const cjsExports = files.map(f => {
    const name = f.replace('.vue', '')
    return `  ${name}: require('./vue3/${f}')`
  }).join(',\n')
  
  const esmExports = files.map(f => {
    const name = f.replace('.vue', '')
    return `export { default as ${name} } from './vue3/${f}'`
  }).join('\n')
  
  const cjsContent = `module.exports = {\n${cjsExports}\n}`
  const esmContent = `// Auto-generated by gulpfile\n${esmExports}`
  
  fs.writeFileSync(path.join(DIST_DIR, 'index.js'), cjsContent, 'utf-8')
  fs.writeFileSync(path.join(DIST_DIR, 'index.esm.js'), esmContent, 'utf-8')
  
  console.log('✅ Built npm package')
}

exports.optimizeSvg = optimizeSvg
exports.build = build
exports.copyTypes = copyTypes
exports.copyUniApp = copyUniApp
exports.clean = clean
exports.buildNpm = buildNpm
exports.default = gulp.series(exports.clean, exports.optimizeSvg, exports.build, exports.copyTypes, exports.copyUniApp, exports.buildNpm)
