const gulp = require('gulp')
const svgo = require('gulp-svgo')
const path = require('path')
const fs = require('fs')

const SRC_DIR = path.join(__dirname, 'src/icons')
const OPTIMIZED_DIR = path.join(__dirname, 'src/icons/optimized')
const DIST_DIR = path.join(__dirname, 'dist')

function clean(done) {
  if (fs.existsSync(DIST_DIR)) {
    fs.rmSync(DIST_DIR, { recursive: true, force: true })
  }
  done()
}

function optimizeSvg() {
  if (fs.existsSync(OPTIMIZED_DIR)) {
    fs.rmSync(OPTIMIZED_DIR, { recursive: true, force: true })
  }
  return gulp
    .src([`${SRC_DIR}/**/*.svg`, `!${OPTIMIZED_DIR}/**/*.svg`])
    .pipe(
      svgo({
        plugins: [
          { removeViewBox: false },
          { removeDimensions: true },
          { removeStyleElement: true },
          { removeScriptElement: true },
          { removeTitle: true },
          { removeDesc: true },
          { removeUselessDefs: true },
          { removeEmptyAttrs: true },
          { removeHiddenElems: true },
          { removeEmptyText: true },
          { convertColors: true },
          { convertPathData: true },
          { mergePaths: true },
          { removeUnusedNS: true },
          { sortAttrs: true },
          { removeEmptyContainers: true },
          { cleanupIds: true },
          { minifyStyles: true },
          { convertTransform: true },
          { convertShapeToPath: true },
          { convertEllipseToCircle: true },
          { moveElemsAttrsToGroup: true },
          { moveGroupAttrsToElems: true },
          { collapseGroups: true },
          { sortDefsChildren: true },
        ],
      })
    )
    .pipe(gulp.dest(OPTIMIZED_DIR))
}

function build() {
  return gulp
    .src('src/components/vue3/*.vue')
    .pipe(gulp.dest('dist/vue3'))
}

function copyTypes() {
  return gulp
    .src(['src/index.d.ts', 'src/web-types.json', 'src/icons.json'])
    .pipe(gulp.dest('dist'))
    .pipe(gulp.dest('dist/uniapp'))
}

function copyUniApp() {
  return gulp
    .src('src/components/uniapp/*')
    .pipe(gulp.dest('dist/uniapp'))
}

function buildUniAppIndex(done) {
  const sourceFile = path.join(__dirname, 'src/components/uniapp/index.ts')
  const targetDir = path.join(__dirname, 'dist/uniapp')
  const targetFile = path.join(targetDir, 'index.js')
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true })
  }
  const content = fs.readFileSync(sourceFile, 'utf-8')
  fs.writeFileSync(targetFile, content, 'utf-8')
  done()
}

async function buildNpm() {
  console.log('Building npm package...')
  
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true })
  }
  
  const vue3Dir = path.join(__dirname, 'src/components/vue3')
  const files = fs.readdirSync(vue3Dir).filter(f => f.endsWith('.vue'))
  
  const cjsExports = files.map(f => {
    const name = f.replace('.vue', '')
    return `  ${name}: require('./vue3/${f}')`
  }).join(',\n')
  
  const esmExports = files.map(f => {
    const name = f.replace('.vue', '')
    return `export { default as ${name} } from './vue3/${f}'`
  }).join('\n')
  
  const cjsContent = `module.exports = {\n${cjsExports}\n}`
  const esmContent = `// Auto-generated by gulpfile\n${esmExports}`
  
  fs.writeFileSync(path.join(DIST_DIR, 'index.js'), cjsContent, 'utf-8')
  fs.writeFileSync(path.join(DIST_DIR, 'index.esm.js'), esmContent, 'utf-8')
  
  console.log('✅ Built npm package')
}

exports.optimizeSvg = optimizeSvg
exports.build = build
exports.copyTypes = copyTypes
exports.copyUniApp = copyUniApp
exports.buildUniAppIndex = buildUniAppIndex
exports.clean = clean
exports.buildNpm = buildNpm
exports.default = gulp.series(exports.clean, exports.optimizeSvg, exports.build, exports.copyTypes, exports.copyUniApp, exports.buildUniAppIndex, exports.buildNpm)
