import fs from 'fs'
import path from 'path'

const ICONS_DIR = path.join(__dirname, 'icons/optimized')
const VUE3_OUTPUT_DIR = path.join(__dirname, 'components/vue3')
const UNIAPP_OUTPUT_DIR = path.join(__dirname, 'components/uniapp')
const INDEX_FILE = path.join(__dirname, 'index.ts')
const TYPES_FILE = path.join(__dirname, 'index.d.ts')

const VUE3_TEMPLATE_PATH = path.join(__dirname, 'components/Vue3IconTemplate.ts')
const UNIAPP_TEMPLATE_PATH = path.join(__dirname, 'components/UniAppIconTemplate.ts')

function toPascalCase(str: string): string {
  return str.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase())
}

function toComponentName(fileName: string): string {
  const name = fileName.replace('.svg', '')
  return `Vu${toPascalCase(name)}`
}

function readFileSync(filePath: string): string {
  return fs.readFileSync(filePath, 'utf-8')
}

function writeFileSync(filePath: string, content: string): void {
  fs.writeFileSync(filePath, content, 'utf-8')
}

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true })
  }
}

function extractSvgContent(svgContent: string): string {
  const match = svgContent.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)
  return match ? match[1].trim() : svgContent
}

function generateVue3Component(
  template: string,
  iconName: string,
  svgContent: string
): string {
  const componentName = toComponentName(iconName)
  const svgPathContent = extractSvgContent(svgContent)
  
  return template
    .replace('<!-- SVG_PATH_CONTENT -->', svgPathContent)
    .replace(/<script setup lang="ts">/, `<script setup lang="ts">\nconst name = '${componentName}'`)
}

function generateUniAppComponent(
  template: string,
  iconName: string,
  svgContent: string
): string {
  const componentName = toComponentName(iconName)
  const svgPathContent = extractSvgContent(svgContent)
  
  return template
    .replace('<!-- SVG_PATH_CONTENT -->', svgPathContent)
    .replace(/<script setup lang="ts">/, `<script setup lang="ts">\nconst name = '${componentName}'`)
}

function generateIndexFile(iconNames: string[]): string {
  const imports = iconNames
    .map(name => {
      const componentName = toComponentName(name)
      return `export { default as ${componentName} } from './components/vue3/${componentName}.vue'`
    })
    .join('\n')

  return `// Auto-generated by build-components.ts\n${imports}`
}

function generateTypesFile(iconNames: string[]): string {
  const typeDefinitions = iconNames
    .map(name => {
      const componentName = toComponentName(name)
      return `  export const ${componentName}: DefineComponent<IconProps>`
    })
    .join('\n')

  return `import { DefineComponent } from 'vue'

export interface IconProps {
  size?: number | string
  color?: string
  className?: string
}

declare module 'vu-icons' {
${typeDefinitions}
}
`
}

function buildComponents(): void {
  console.log('🚀 Starting component generation...')

  ensureDir(ICONS_DIR)
  ensureDir(VUE3_OUTPUT_DIR)
  ensureDir(UNIAPP_OUTPUT_DIR)

  const svgFiles = fs.readdirSync(ICONS_DIR).filter(file => file.endsWith('.svg'))
  
  if (svgFiles.length === 0) {
    console.log('⚠️  No SVG files found in icons/optimized directory')
    console.log('💡 Run "npm run optimize:svg" first to optimize SVG files')
    return
  }

  const vue3Template = readFileSync(VUE3_TEMPLATE_PATH)
  const uniappTemplate = readFileSync(UNIAPP_TEMPLATE_PATH)

  svgFiles.forEach(svgFile => {
    const svgContent = readFileSync(path.join(ICONS_DIR, svgFile))
    const componentName = toComponentName(svgFile)

    const vue3Component = generateVue3Component(vue3Template, svgFile, svgContent)
    const uniAppComponent = generateUniAppComponent(uniappTemplate, svgFile, svgContent)

    writeFileSync(path.join(VUE3_OUTPUT_DIR, `${componentName}.vue`), vue3Component)
    writeFileSync(path.join(UNIAPP_OUTPUT_DIR, `${componentName}.vue`), uniAppComponent)

    console.log(`✅ Generated: ${componentName}`)
  })

  const indexContent = generateIndexFile(svgFiles)
  writeFileSync(INDEX_FILE, indexContent)

  const typesContent = generateTypesFile(svgFiles)
  writeFileSync(TYPES_FILE, typesContent)

  console.log(`\n✨ Successfully generated ${svgFiles.length} components`)
  console.log(`📦 Vue3 components: ${VUE3_OUTPUT_DIR}`)
  console.log(`📦 UniApp components: ${UNIAPP_OUTPUT_DIR}`)
  console.log(`📄 Index file: ${INDEX_FILE}`)
  console.log(`📄 Types file: ${TYPES_FILE}`)
}

buildComponents()
