import fs from 'fs'
import path from 'path'

const ICONS_DIR = path.join(__dirname, 'icons/optimized')
const VUE3_OUTPUT_DIR = path.join(__dirname, 'components/vue3')
const UNIAPP_OUTPUT_DIR = path.join(__dirname, 'components/uniapp')
const INDEX_FILE = path.join(__dirname, 'index.ts')
const UNIAPP_INDEX_FILE = path.join(__dirname, 'components/uniapp/index.ts')
const TYPES_FILE = path.join(__dirname, 'index.d.ts')

const ICONS_JSON_FILE = path.join(__dirname, 'icons.json')
const WEB_TYPES_FILE = path.join(__dirname, 'web-types.json')

const VUE3_TEMPLATE_PATH = path.join(__dirname, 'components/Vue3IconTemplate.ts')
const UNIAPP_TEMPLATE_PATH = path.join(__dirname, 'components/UniAppIconTemplate.ts')

function toPascalCase(str: string): string {
  return str.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase())
}

function toComponentName(fileName: string): string {
  const name = fileName.replace('.svg', '')
  return `Vu${toPascalCase(name)}`
}

function readFileSync(filePath: string): string {
  return fs.readFileSync(filePath, 'utf-8')
}

function writeFileSync(filePath: string, content: string): void {
  let retries = 3
  while (retries > 0) {
    try {
      fs.writeFileSync(filePath, content, 'utf-8')
      return
    } catch (error: any) {
      if (error.code === 'EPERM' || error.code === 'EACCES') {
        retries--
        if (retries > 0) {
          const waitTime = 500
          Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, waitTime)
          continue
        }
      }
      throw error
    }
  }
}

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true })
  }
}

function resetDir(dirPath: string): void {
  if (fs.existsSync(dirPath)) {
    fs.rmSync(dirPath, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 })
  }
  fs.mkdirSync(dirPath, { recursive: true })
}

function extractSvgContent(svgContent: string): string {
  const match = svgContent.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)
  return match ? match[1].trim() : svgContent
}

function extractViewBox(svgContent: string): string {
  const match = svgContent.match(/viewBox="([^"]+)"/)
  return match ? match[1] : '0 0 24 24'
}

function generateVue3Component(
  template: string,
  iconName: string,
  svgContent: string
): string {
  const componentName = toComponentName(iconName)
  const svgPathContent = extractSvgContent(svgContent)
  const viewBox = extractViewBox(svgContent)
  
  return template
    .replace(/<!-- SVG_PATH_CONTENT -->/g, svgPathContent)
    .replace(/<!-- VIEW_BOX -->/g, viewBox)
    .replace(/<script setup lang="ts">/, `<script setup lang="ts">\nconst name = '${componentName}'`)
}

function generateUniAppComponent(
  template: string,
  iconName: string,
  svgContent: string
): string {
  const componentName = toComponentName(iconName)
  const svgPathContent = extractSvgContent(svgContent)
  const viewBox = extractViewBox(svgContent)
  
  return template
    .replace(/<!-- SVG_PATH_CONTENT -->/g, svgPathContent)
    .replace(/<!-- VIEW_BOX -->/g, viewBox)
    .replace(/<script setup lang="ts">/, `<script setup lang="ts">\nconst name = '${componentName}'`)
}

function generateIndexFile(iconNames: string[], isUniApp = false): string {
  const imports = iconNames
    .map(name => {
      const componentName = toComponentName(name)
      const importPath = isUniApp ? `./${componentName}.vue` : `./components/vue3/${componentName}.vue`
      return `export { default as ${componentName} } from '${importPath}'`
    })
    .join('\n')

  return `// Auto-generated by build-components.ts\n${imports}`
}

function generateTypesFile(iconNames: string[]): string {
  const typeDefinitions = iconNames
    .map(name => {
      const componentName = toComponentName(name)
      return `  export const ${componentName}: DefineComponent<IconProps>`
    })
    .join('\n')

  return `import { DefineComponent } from 'vue'

export interface IconProps {
  /**
   * Icon size, supports number (px) or string (e.g. '1rem', '24px')
   * @default 24
   */
  size?: number | string
  /**
   * Icon color
   * @default 'currentColor'
   */
  color?: string
  /**
   * Custom class name
   * @default ''
   */
  className?: string
  /**
   * Whether to spin the icon
   * @default false
   */
  spin?: boolean
}

declare module 'vu-icons' {
${typeDefinitions}
}

declare module 'vu-icons/uniapp' {
${typeDefinitions}
}
`
}

function generateWebTypes(iconNames: string[]): string {
  const components = iconNames.map(name => {
    const componentName = toComponentName(name)
    return {
      "name": componentName,
      "source": {
        "symbol": componentName
      },
      "description": `Vue 3 & UniApp Icon ${componentName}`,
      "props": [
        {
          "name": "size",
          "type": ["number", "string"],
          "default": "24",
          "description": "Icon size"
        },
        {
          "name": "color",
          "type": "string",
          "default": "currentColor",
          "description": "Icon color"
        },
        {
          "name": "className",
          "type": "string",
          "default": "",
          "description": "Custom class name"
        },
        {
          "name": "spin",
          "type": "boolean",
          "default": "false",
          "description": "Spin animation"
        }
      ]
    }
  })

  return JSON.stringify({
    "$schema": "https://raw.githubusercontent.com/JetBrains/web-types/master/schema/web-types.json",
    "framework": "vue",
    "name": "vu-icons",
    "version": require('../package.json').version,
    "contributions": {
      "html": {
        "tags": components
      }
    }
  }, null, 2)
}

function getAllSvgFiles(dir: string, fileList: string[] = []): string[] {
  const files = fs.readdirSync(dir)

  files.forEach(file => {
    const filePath = path.join(dir, file)
    const stat = fs.statSync(filePath)

    if (stat.isDirectory()) {
      getAllSvgFiles(filePath, fileList)
    } else {
      if (file.endsWith('.svg')) {
        fileList.push(filePath)
      }
    }
  })

  return fileList
}

function buildComponents(): void {
  console.log('🚀 Starting component generation...')

  ensureDir(ICONS_DIR)
  resetDir(VUE3_OUTPUT_DIR)
  resetDir(UNIAPP_OUTPUT_DIR)

  const svgFiles = getAllSvgFiles(ICONS_DIR).sort((a, b) => a.localeCompare(b))
  
  if (svgFiles.length === 0) {
    console.log('⚠️  No SVG files found in icons/optimized directory')
    console.log('💡 Run "npm run optimize:svg" first to optimize SVG files')
    return
  }

  const vue3Template = readFileSync(VUE3_TEMPLATE_PATH)
  const uniappTemplate = readFileSync(UNIAPP_TEMPLATE_PATH)

  const processedNames: string[] = []
  const processedNameSet = new Set<string>()

  svgFiles.forEach(svgFilePath => {
    const svgContent = readFileSync(svgFilePath)
    const svgFileName = path.basename(svgFilePath) // Use basename to keep component name flat
    const componentName = toComponentName(svgFileName)

    // Check for duplicate component names
    if (processedNameSet.has(svgFileName)) {
        console.warn(`⚠️  Duplicate icon name found: ${svgFileName}. Skipping ${svgFilePath}`)
        return
    }
    processedNameSet.add(svgFileName)
    processedNames.push(svgFileName)

    const vue3Component = generateVue3Component(vue3Template, svgFileName, svgContent)
    const uniAppComponent = generateUniAppComponent(uniappTemplate, svgFileName, svgContent)

    writeFileSync(path.join(VUE3_OUTPUT_DIR, `${componentName}.vue`), vue3Component)
    writeFileSync(path.join(UNIAPP_OUTPUT_DIR, `${componentName}.vue`), uniAppComponent)

    console.log(`✅ Generated: ${componentName}`)
  })

  const indexContent = generateIndexFile(processedNames)
  writeFileSync(INDEX_FILE, indexContent)



  const uniappIndexContent = generateIndexFile(processedNames, true)
  writeFileSync(UNIAPP_INDEX_FILE, uniappIndexContent)
  const typesContent = generateTypesFile(processedNames)
  writeFileSync(TYPES_FILE, typesContent)

  const iconsJsonContent = JSON.stringify(processedNames.map(name => toComponentName(name)), null, 2)
  writeFileSync(ICONS_JSON_FILE, iconsJsonContent)

  const webTypesContent = generateWebTypes(processedNames)
  writeFileSync(WEB_TYPES_FILE, webTypesContent)

  console.log(`\n✨ Successfully generated ${processedNames.length} components`)
  console.log(`📦 Vue3 components: ${VUE3_OUTPUT_DIR}`)
  console.log(`📦 UniApp components: ${UNIAPP_OUTPUT_DIR}`)
  console.log(`📄 Index file: ${INDEX_FILE}`)
  console.log(`📄 Types file: ${TYPES_FILE}`)
  console.log(`📄 Icons JSON: ${ICONS_JSON_FILE}`)
  console.log(`📄 Web Types: ${WEB_TYPES_FILE}`)
}

buildComponents()
