import { DefineComponent } from 'vue'

export interface IconProps {
  size?: number | string
  color?: string
  className?: string
}

declare module 'vu-icons' {
  export const VuActive: DefineComponent<IconProps>
  export const VuAdd: DefineComponent<IconProps>
  export const VuAlarm: DefineComponent<IconProps>
  export const VuAnchor: DefineComponent<IconProps>
  export const VuAppointment: DefineComponent<IconProps>
  export const VuAreaChart: DefineComponent<IconProps>
  export const VuArrowDownLeft: DefineComponent<IconProps>
  export const VuArrowDownRight: DefineComponent<IconProps>
  export const VuArrowDown: DefineComponent<IconProps>
  export const VuArrowLeft: DefineComponent<IconProps>
  export const VuArrowRight: DefineComponent<IconProps>
  export const VuArrowUpLeft: DefineComponent<IconProps>
  export const VuArrowUpRight: DefineComponent<IconProps>
  export const VuArrowUp: DefineComponent<IconProps>
  export const VuArrowsExpand: DefineComponent<IconProps>
  export const VuArrowsHorizontal: DefineComponent<IconProps>
  export const VuAt: DefineComponent<IconProps>
  export const VuAvatar: DefineComponent<IconProps>
  export const VuBankCard: DefineComponent<IconProps>
  export const VuBarChart: DefineComponent<IconProps>
  export const VuBarcode: DefineComponent<IconProps>
  export const VuBattery: DefineComponent<IconProps>
  export const VuBell: DefineComponent<IconProps>
  export const VuBike: DefineComponent<IconProps>
  export const VuBill: DefineComponent<IconProps>
  export const VuBluetooth: DefineComponent<IconProps>
  export const VuBook: DefineComponent<IconProps>
  export const VuBottomBar: DefineComponent<IconProps>
  export const VuBreadcrumb: DefineComponent<IconProps>
  export const VuBus: DefineComponent<IconProps>
  export const VuCalculator: DefineComponent<IconProps>
  export const VuCamera: DefineComponent<IconProps>
  export const VuCar: DefineComponent<IconProps>
  export const VuCast: DefineComponent<IconProps>
  export const VuCategory: DefineComponent<IconProps>
  export const VuCharging: DefineComponent<IconProps>
  export const VuCheck: DefineComponent<IconProps>
  export const VuCheckup: DefineComponent<IconProps>
  export const VuChevronDown: DefineComponent<IconProps>
  export const VuChevronLeft: DefineComponent<IconProps>
  export const VuChevronRight: DefineComponent<IconProps>
  export const VuChevronUp: DefineComponent<IconProps>
  export const VuClassroom: DefineComponent<IconProps>
  export const VuClock: DefineComponent<IconProps>
  export const VuClose: DefineComponent<IconProps>
  export const VuCoffee: DefineComponent<IconProps>
  export const VuComment: DefineComponent<IconProps>
  export const VuCompleted: DefineComponent<IconProps>
  export const VuCopy: DefineComponent<IconProps>
  export const VuCoupon: DefineComponent<IconProps>
  export const VuCourse: DefineComponent<IconProps>
  export const VuCreditCard: DefineComponent<IconProps>
  export const VuCut: DefineComponent<IconProps>
  export const VuDataCompare: DefineComponent<IconProps>
  export const VuDataExport: DefineComponent<IconProps>
  export const VuDataFilter: DefineComponent<IconProps>
  export const VuDataRefresh: DefineComponent<IconProps>
  export const VuDelete: DefineComponent<IconProps>
  export const VuDelivery: DefineComponent<IconProps>
  export const VuDisabled: DefineComponent<IconProps>
  export const VuDislike: DefineComponent<IconProps>
  export const VuDivide: DefineComponent<IconProps>
  export const VuDot: DefineComponent<IconProps>
  export const VuDoughnutChart: DefineComponent<IconProps>
  export const VuDownload: DefineComponent<IconProps>
  export const VuEdit: DefineComponent<IconProps>
  export const VuEnter: DefineComponent<IconProps>
  export const VuEqual: DefineComponent<IconProps>
  export const VuError: DefineComponent<IconProps>
  export const VuExam: DefineComponent<IconProps>
  export const VuExitFullscreen: DefineComponent<IconProps>
  export const VuFailure: DefineComponent<IconProps>
  export const VuFastBackward: DefineComponent<IconProps>
  export const VuFastForward: DefineComponent<IconProps>
  export const VuFavorite: DefineComponent<IconProps>
  export const VuFile: DefineComponent<IconProps>
  export const VuFilter: DefineComponent<IconProps>
  export const VuFinance: DefineComponent<IconProps>
  export const VuFitness: DefineComponent<IconProps>
  export const VuFolder: DefineComponent<IconProps>
  export const VuFollow: DefineComponent<IconProps>
  export const VuFollowers: DefineComponent<IconProps>
  export const VuFood: DefineComponent<IconProps>
  export const VuForward: DefineComponent<IconProps>
  export const VuFullscreen: DefineComponent<IconProps>
  export const VuFunnelChart: DefineComponent<IconProps>
  export const VuGraduationCap: DefineComponent<IconProps>
  export const VuGroupBuy: DefineComponent<IconProps>
  export const VuHint: DefineComponent<IconProps>
  export const VuHistory: DefineComponent<IconProps>
  export const VuHome: DefineComponent<IconProps>
  export const VuHomework: DefineComponent<IconProps>
  export const VuHospital: DefineComponent<IconProps>
  export const VuHotel: DefineComponent<IconProps>
  export const VuImage: DefineComponent<IconProps>
  export const VuInProgress: DefineComponent<IconProps>
  export const VuIncomplete: DefineComponent<IconProps>
  export const VuInfo: DefineComponent<IconProps>
  export const VuInsurance: DefineComponent<IconProps>
  export const VuInvoice: DefineComponent<IconProps>
  export const VuLaboratory: DefineComponent<IconProps>
  export const VuLibrary: DefineComponent<IconProps>
  export const VuLike: DefineComponent<IconProps>
  export const VuLineChart: DefineComponent<IconProps>
  export const VuLink: DefineComponent<IconProps>
  export const VuLoading: DefineComponent<IconProps>
  export const VuLocation: DefineComponent<IconProps>
  export const VuLockScreen: DefineComponent<IconProps>
  export const VuLock: DefineComponent<IconProps>
  export const VuMask: DefineComponent<IconProps>
  export const VuMedicalRecord: DefineComponent<IconProps>
  export const VuMedicine: DefineComponent<IconProps>
  export const VuMenu: DefineComponent<IconProps>
  export const VuMessagePrivate: DefineComponent<IconProps>
  export const VuMessage: DefineComponent<IconProps>
  export const VuMinus: DefineComponent<IconProps>
  export const VuMoon: DefineComponent<IconProps>
  export const VuMovie: DefineComponent<IconProps>
  export const VuMultiply: DefineComponent<IconProps>
  export const VuMusic: DefineComponent<IconProps>
  export const VuNavigationDot: DefineComponent<IconProps>
  export const VuNavigation: DefineComponent<IconProps>
  export const VuNote: DefineComponent<IconProps>
  export const VuPackage: DefineComponent<IconProps>
  export const VuPagination: DefineComponent<IconProps>
  export const VuPaste: DefineComponent<IconProps>
  export const VuPause: DefineComponent<IconProps>
  export const VuPaymentMedical: DefineComponent<IconProps>
  export const VuPayment: DefineComponent<IconProps>
  export const VuPen: DefineComponent<IconProps>
  export const VuPencil: DefineComponent<IconProps>
  export const VuPieChart: DefineComponent<IconProps>
  export const VuPlane: DefineComponent<IconProps>
  export const VuPlay: DefineComponent<IconProps>
  export const VuPoints: DefineComponent<IconProps>
  export const VuProduct: DefineComponent<IconProps>
  export const VuQrcode: DefineComponent<IconProps>
  export const VuRadarChart: DefineComponent<IconProps>
  export const VuRainy: DefineComponent<IconProps>
  export const VuRead: DefineComponent<IconProps>
  export const VuRecharge: DefineComponent<IconProps>
  export const VuRedo: DefineComponent<IconProps>
  export const VuRefresh: DefineComponent<IconProps>
  export const VuRefund: DefineComponent<IconProps>
  export const VuReportMedical: DefineComponent<IconProps>
  export const VuReport: DefineComponent<IconProps>
  export const VuRuler: DefineComponent<IconProps>
  export const VuScan: DefineComponent<IconProps>
  export const VuScatterChart: DefineComponent<IconProps>
  export const VuScreenshot: DefineComponent<IconProps>
  export const VuSearch: DefineComponent<IconProps>
  export const VuSelected: DefineComponent<IconProps>
  export const VuSettings: DefineComponent<IconProps>
  export const VuShare: DefineComponent<IconProps>
  export const VuShoppingBag: DefineComponent<IconProps>
  export const VuShoppingCart: DefineComponent<IconProps>
  export const VuSidebar: DefineComponent<IconProps>
  export const VuSignal: DefineComponent<IconProps>
  export const VuSkipBackward: DefineComponent<IconProps>
  export const VuSkipForward: DefineComponent<IconProps>
  export const VuSort: DefineComponent<IconProps>
  export const VuSpace: DefineComponent<IconProps>
  export const VuSplitBill: DefineComponent<IconProps>
  export const VuSports: DefineComponent<IconProps>
  export const VuSquare: DefineComponent<IconProps>
  export const VuStar: DefineComponent<IconProps>
  export const VuStatistics: DefineComponent<IconProps>
  export const VuStethoscope: DefineComponent<IconProps>
  export const VuStop: DefineComponent<IconProps>
  export const VuSubway: DefineComponent<IconProps>
  export const VuSuccess: DefineComponent<IconProps>
  export const VuSun: DefineComponent<IconProps>
  export const VuSunny: DefineComponent<IconProps>
  export const VuTag: DefineComponent<IconProps>
  export const VuTakeout: DefineComponent<IconProps>
  export const VuThermometer: DefineComponent<IconProps>
  export const VuToBottom: DefineComponent<IconProps>
  export const VuToTop: DefineComponent<IconProps>
  export const VuTopBar: DefineComponent<IconProps>
  export const VuTrain: DefineComponent<IconProps>
  export const VuTransfer: DefineComponent<IconProps>
  export const VuTravel: DefineComponent<IconProps>
  export const VuTriangle: DefineComponent<IconProps>
  export const VuUndo: DefineComponent<IconProps>
  export const VuUnfollow: DefineComponent<IconProps>
  export const VuUnlock: DefineComponent<IconProps>
  export const VuUnread: DefineComponent<IconProps>
  export const VuUnselected: DefineComponent<IconProps>
  export const VuUpload: DefineComponent<IconProps>
  export const VuUser: DefineComponent<IconProps>
  export const VuVideo: DefineComponent<IconProps>
  export const VuVolumeDown: DefineComponent<IconProps>
  export const VuVolumeOff: DefineComponent<IconProps>
  export const VuVolumeOn: DefineComponent<IconProps>
  export const VuVolumeUp: DefineComponent<IconProps>
  export const VuWalk: DefineComponent<IconProps>
  export const VuWallet: DefineComponent<IconProps>
  export const VuWarning: DefineComponent<IconProps>
  export const VuWaterfallChart: DefineComponent<IconProps>
  export const VuWifi: DefineComponent<IconProps>
  export const VuWishlist: DefineComponent<IconProps>
  export const VuWithdraw: DefineComponent<IconProps>
  export const VuZoomIn: DefineComponent<IconProps>
  export const VuZoomOut: DefineComponent<IconProps>
}
